### ISSUE TITLE
Please consider clarifying in your readme that PROSE is not open source

### ISSUE THREAD

**Issue by simmdan** [dfinke/PSProse#2]
Your project is very cool, and I'm excited to see that you have been able to build some interesting solutions based on PROSE!

I noticed, however, that your readme says that PROSE Is open source.  Right now the Microsoft PROSE SDK for .Net is available publicly in binary form for non-commercial use only.  PROSE technologies are built into various Microsoft products which may be used for commercial purposes, but the PROSE SDK itself is intended for research/exploration not for third parties to build commercial solutions on it.

That may change in the future, but for now, I just don't want someone to be misled.

Thanks,
Danny (from the PROSE team)

**Comment by dfinke** [comment]
Thank you for the clarification. Let me know if I missed any other points.

**Comment by simmdan** [comment]
Looks good.  Thanks for making the change.
