### ISSUE TITLE
Where is "Split Text Buddy" UI?

### ISSUE THREAD

**Issue by dprice** [dfinke/PSProse#4]
I just installed your module via your twitter directions:

`Install-Module PSProse`

I did this to see the available commands:
```powershell
D:\Temp\> Get-Command -Module PSProse

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-JSONData                                       1.1.0      PSProse
Function        Invoke-SplitText                                   1.1.0      PSProse
Function        New-JSONSession                                    1.1.0      PSProse
```

I ran this with some pipe-delimited data I had kicking around:
```powershell
D:\Temp> Invoke-SplitText -File D:\Temp\Company.txt

Col1              Col2
----              ----
CompanyIdentifier Name|ShortName|TimeZoneCode|CompanyTypeCode|...
<can't show customer data>
```

This is cool! But where is the UI you demoed in the twitter gif?

Thanks,
Derek

**Comment by dfinke** [comment]
Where the module is installed, there is the `splittextui.ps1`. Run that and pass a file to it.

**Comment by dprice** [comment]
I tried it quickly and it was a bit quirky. I'm going on vacation so I'll experiment more next week. Thanks!
